# Generated by Django 6.1 on 2026-09-08 13:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('art_image', models.URLField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
