# Generated by Django 6.1 on 2026-09-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='art_image',
            field=models.ImageField(null=True, upload_to='static/img/'),
        ),
    ]
