# Generated by Django 6.1 on 2026-09-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='tags',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
