# Generated by Django 6.1 on 2026-09-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_artwork_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='tags',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
