# Generated by Django 6.1 on 2026-09-24 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_project_starred_by_alter_artwork_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_artworks', to=settings.AUTH_USER_MODEL),
        ),
    ]
